export const query_keys = {
  CATEGORY_LIST: 'CATEGORY_LIST',
  USER_LIST: 'USER_LIST',
  REPORTED_PRODUCT_LIST: 'REPORTED_PRODUCT_LIST',
  REPORTED_SHOP_LIST: 'REPORTED_SHOP_LIST',
  TRANSACTION: 'TRANSACTION',
  ORDER_LIST: 'ORDER_LIST',
  WITHDRAW: 'WITHDRAW',
}
